/**
 * Handover service (H9 — "proper" Claude Code handover).
 *
 * Replaces the old "one markdown file + external terminal" flow with a real,
 * reusable HANDOVER BUNDLE plus an optional in-app agentic run. See
 * docs/specs/2026-07-11-pluggable-brains-and-handover.md §E.
 *
 *   handover/<timestamped-slug>/
 *     HANDOVER.md          # the generated handoff prompt (claude_code_prompt core)
 *     README.md            # "generated by HiDock Next — start with HANDOVER.md"
 *     manifest.json        # { generatedAt, brain, source ids, files }
 *     context/
 *       transcript.md      # full transcript
 *       summary.md         # analysis summary
 *       action-items.md    # extracted action items + detected actionables
 *       decisions.md       # key points / decisions
 *       meeting.json       # { subject, date, attendees, meetingId, recordingIds }
 *     RUN.log              # (created only when the agent is run) run progress/result
 *
 * The bundle assembler is pure filesystem + DB reads (fully unit-testable via
 * injected data + a real temp dir). The agentic run resolves an AGENTIC brain via
 * the BrainRouter (task 'handover', capability 'agentic') and uses the brain's
 * `generate()` as the invocation surface — honouring the never-throw / null
 * contract (a null result is a SURFACED failure, not silence). No adapter internals
 * are touched here; this service only consumes the public brains seam.
 */
import { mkdirSync, writeFileSync, appendFileSync, realpathSync, lstatSync, readFileSync } from 'fs'
import { join, parse, relative, resolve, sep } from 'path'
import { homedir } from 'os'
import { randomBytes, randomUUID } from 'crypto'
import {
  getTranscriptByRecordingId,
  getMeetingById,
  getRecordingById,
  queryOne,
  queryAll,
} from './database'
import { isRecordingEligible, isCaptureEligible, filterEligibleRecordingIds } from './recording-eligibility'
import { getBrainRouter, getBrainRegistry } from './brains'
import type { AIBrain } from './brains'
import { getEventBus } from './event-bus'

/** Source the handover was generated from (any subset resolves the rest via DB). */
export interface HandoverSourceRef {
  actionableId?: string
  knowledgeCaptureId?: string
  meetingId?: string
  recordingId?: string
}

/** Small, serialisable record of what the bundle contains + where it came from. */
export interface HandoverManifest {
  slug: string
  title: string
  generatedAt: string
  brain: { id: string; label: string } | null
  source: {
    actionableId: string | null
    knowledgeCaptureId: string | null
    meetingId: string | null
    recordingIds: string[]
  }
  /** Bundle-relative paths of every file written (POSIX separators). */
  files: string[]
}

export interface AssembleBundleParams {
  /** Directory the bundle folder is created under (the target repo/dir). */
  targetDir: string
  /** The HANDOVER.md core — reuse of the claude_code_prompt template output. */
  handoverContent: string
  source: HandoverSourceRef
  /** The brain that will run (or ran) the handover, recorded in the manifest. */
  brain?: { id: string; label: string } | null
  /**
   * Additional canonical paths (app install dir, userData, …) the caller wants
   * refused as targets, on top of the built-in OS-protected list. The IPC handler
   * passes the Electron app paths here (this module stays Electron-free).
   */
  extraProtectedPaths?: string[]
  /** Injected for tests. Defaults to a live clock. */
  now?: () => Date
  /** Injected for tests. Defaults to DB-backed readers. */
  data?: Partial<HandoverDataDeps>
}

export interface AssembleBundleResult {
  /**
   * Opaque id for this bundle in the main-process registry. The ONLY token the
   * renderer may pass back to run the agent — paths from the renderer are never
   * trusted for execution.
   */
  bundleId: string
  bundleDir: string
  handoverPath: string
  /** The canonicalized (realpath) target directory the bundle was written under. */
  targetDir: string
  manifest: HandoverManifest
}

/**
 * DB reader seam. Defaults bind to database.ts; tests pass fakes so the assembler
 * can be exercised against a real temp directory with no database.
 */
export interface HandoverDataDeps {
  getActionable: (id: string) => { source_knowledge_id: string | null } | undefined
  getKnowledgeCapture: (
    id: string
  ) =>
    | { id: string; title?: string; summary?: string; source_recording_id?: string | null; meeting_id?: string | null; captured_at?: string }
    | undefined
  getRecording: (id: string) => { id: string; filename?: string; meeting_id?: string | null; date_recorded?: string } | undefined
  getTranscript: (
    recordingId: string
  ) => { full_text?: string; summary?: string; action_items?: string; key_points?: string; topics?: string } | undefined
  getMeeting: (id: string) => { id: string; subject?: string; start_time?: string; attendees?: string } | undefined
  getActionablesForKnowledge: (knowledgeId: string) => Array<{ title: string; description?: string; type?: string; status?: string }>
  /** RE7-2 (round-7) — the shared fail-closed recording-eligibility boundary. */
  isRecordingEligible: (recordingId: string) => boolean
  /**
   * ADV16-4 (round-17) — the shared fail-closed CAPTURE-eligibility boundary. A
   * STANDALONE capture has no recordingId, so the recording gate alone would let
   * its title/summary/actionables through unchecked. Gate every resolved capture
   * through this (deleted_at + standalone quality, or recording delegation).
   */
  isCaptureEligible: (captureId: string) => boolean
}

const defaultDataDeps: HandoverDataDeps = {
  getActionable: (id) => queryOne<{ source_knowledge_id: string | null }>('SELECT source_knowledge_id FROM actionables WHERE id = ?', [id]),
  getKnowledgeCapture: (id) =>
    queryOne('SELECT id, title, summary, source_recording_id, meeting_id, captured_at FROM knowledge_captures WHERE id = ?', [id]),
  getRecording: (id) => getRecordingById(id) as any,
  getTranscript: (recordingId) => getTranscriptByRecordingId(recordingId) as any,
  getMeeting: (id) => getMeetingById(id) as any,
  getActionablesForKnowledge: (knowledgeId) =>
    queryAll<{ title: string; description?: string; type?: string; status?: string }>(
      'SELECT title, description, type, status FROM actionables WHERE source_knowledge_id = ? ORDER BY created_at',
      [knowledgeId]
    ),
  isRecordingEligible: (recordingId) => isRecordingEligible(recordingId),
  isCaptureEligible: (captureId) => isCaptureEligible(captureId),
}

/** RE7-2 — thrown when a handover's source recording is excluded / ineligible. */
export const HANDOVER_INELIGIBLE_ERROR =
  'Handover refused — the source recording is excluded (trashed / personal / low-value) or its eligibility could not be verified.'

interface ResolvedSource {
  actionableId: string | null
  knowledgeCaptureId: string | null
  meetingId: string | null
  recordingIds: string[]
  title: string
  transcriptText: string
  summaryText: string
  actionItemsText: string
  decisionsText: string
  meetingJson: {
    subject: string | null
    date: string | null
    attendees: string[]
    meetingId: string | null
    recordingIds: string[]
    knowledgeCaptureId: string | null
  }
}

/** Lowercase, hyphenated, bounded slug from a free-text title. */
export function slugify(title: string): string {
  return (
    title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '')
      .slice(0, 60) || 'handover'
  )
}

/** Timestamped directory prefix: YYYY-MM-DD-HHmmss (local time). */
function timestampSlug(now: Date): string {
  const p = (n: number) => String(n).padStart(2, '0')
  return `${now.getFullYear()}-${p(now.getMonth() + 1)}-${p(now.getDate())}-${p(now.getHours())}${p(now.getMinutes())}${p(now.getSeconds())}`
}

// ── Target validation, bundle registry, atomic reservation (security) ─────────

/** Normalize a path for comparison: canonical form, lowercased on Windows. */
function comparable(p: string): string {
  const r = resolve(p)
  return process.platform === 'win32' ? r.toLowerCase() : r
}

/** OS-protected roots the handover must never write into (built-in list). */
function builtinProtectedPaths(env: NodeJS.ProcessEnv = process.env): string[] {
  const list: string[] = []
  for (const v of [env.SystemRoot, env.windir, env.ProgramFiles, env['ProgramFiles(x86)'], env.ProgramData]) {
    if (v && v.trim()) list.push(v)
  }
  if (process.platform !== 'win32') list.push('/etc', '/usr', '/bin', '/sbin', '/boot', '/System', '/Library')
  return list
}

/**
 * All comparable forms of a protected path: the resolved string AND (when it
 * exists) its realpath. Canonicalizing kills subst/mapped-drive aliases and
 * on-disk case variants — a target can't dodge a protected check by naming the
 * same directory through a different spelling.
 */
function protectedForms(p: string): string[] {
  const forms = [comparable(p)]
  try {
    const real = comparable(realpathSync(p))
    if (!forms.includes(real)) forms.push(real)
  } catch {
    /* protected path doesn't exist on this machine — the resolved form still applies */
  }
  return forms
}

/** The user's home directory (env override for tests, else os.homedir()). */
function resolveHomeDir(env: NodeJS.ProcessEnv): string | null {
  const fromEnv = (process.platform === 'win32' ? env.USERPROFILE : env.HOME)?.trim()
  if (fromEnv) return fromEnv
  try {
    return homedir()
  } catch {
    return null
  }
}

/**
 * Canonicalize and vet a renderer-supplied target directory. Throws with a
 * user-facing message when the target is unusable:
 *   - does not exist / not a directory (realpath resolves symlinks — the
 *     CANONICAL location is what gets vetted and used from here on);
 *   - is a filesystem root (C:\, /);
 *   - is the user-profile / home directory ITSELF (an autonomous agent must not
 *     get the whole profile — documents, credentials, every repo — as its cwd;
 *     deeper subdirectories like home\repos\project remain fine);
 *   - is (or is inside) a protected OS location or a caller-supplied protected
 *     path (app install dir, userData — passed by the IPC handler);
 *   - CONTAINS (is an ancestor of) any protected path — otherwise an agent
 *     cwd'd above e.g. userData could still reach it.
 * Every protected path is compared in canonical (realpath) form, case-insensitive
 * on win32. Returns the canonical real path.
 */
export function validateTargetDir(
  targetDir: string,
  extraProtectedPaths: string[] = [],
  env: NodeJS.ProcessEnv = process.env
): string {
  let canonical: string
  try {
    canonical = realpathSync(targetDir)
  } catch {
    throw new Error(`The handover folder does not exist: ${targetDir}`)
  }
  if (!lstatSync(canonical).isDirectory()) {
    throw new Error(`The handover target is not a directory: ${targetDir}`)
  }

  const c = comparable(canonical)
  const root = parse(canonical).root
  if (c === comparable(root)) {
    throw new Error('The handover target cannot be a filesystem root. Pick a project folder.')
  }

  // Home/profile root: EXACT match only — subdirectories are legitimate targets.
  const home = resolveHomeDir(env)
  if (home && protectedForms(home).includes(c)) {
    throw new Error('The handover target cannot be your user profile folder. Pick a specific project folder inside it.')
  }

  for (const protectedPath of [...builtinProtectedPaths(env), ...extraProtectedPaths]) {
    for (const p of protectedForms(protectedPath)) {
      if (c === p || c.startsWith(p + sep)) {
        throw new Error(`The handover target is inside a protected location (${protectedPath}). Pick a project folder.`)
      }
      // Ancestor check: a target CONTAINING a protected path hands the agent
      // that protected path too.
      if (p.startsWith(c + sep)) {
        throw new Error(`The handover target contains a protected location (${protectedPath}). Pick a narrower project folder.`)
      }
    }
  }
  return canonical
}

/**
 * Main-process bundle registry. `handover:runAgent` accepts ONLY an opaque
 * bundleId minted here — a renderer can never point the runner at an arbitrary
 * path.
 *
 * SESSION-ONLY BY DESIGN: the registry is an in-memory Map, so a bundleId is
 * runnable only in the app session that created it. After an app restart every
 * previously-issued id is stale — runAgent/`handover:runAgent` then return the
 * friendly "bundle expired — write it again" error rather than trusting any
 * persisted path. The bundle FILES on disk survive fine (open-in-terminal /
 * manual use); only the in-app run token expires.
 */
export interface BundleRecord {
  bundleDir: string
  targetDir: string
  createdAt: string
}

/** Friendly stale/forged-id message (also shown after an app restart). */
export const BUNDLE_EXPIRED_ERROR =
  'This handover bundle has expired (bundles can only be run from the session that wrote them). Write the bundle again and retry.'

const bundleRegistry = new Map<string, BundleRecord>()
/** BundleIds with an agent run currently in flight (concurrency guard). */
const activeRuns = new Set<string>()

export function getRegisteredBundle(bundleId: string): BundleRecord | undefined {
  return bundleRegistry.get(bundleId)
}

/** Test helper: clear the registry + active-run tracking. */
export function resetHandoverRegistry(): void {
  bundleRegistry.clear()
  activeRuns.clear()
}

/**
 * Atomically reserve a fresh bundle directory: `mkdirSync(..., recursive: false)`
 * either creates it or throws EEXIST — no check-then-use window. On collision
 * (same slug in the same second, or a concurrent create) retry with a random
 * suffix. Never reuses or overwrites an existing directory.
 */
function reserveBundleDir(parentDir: string, slug: string): string {
  const candidates = [join(parentDir, slug)]
  for (let i = 0; i < 8; i++) {
    candidates.push(join(parentDir, `${slug}-${randomBytes(3).toString('hex')}`))
  }
  for (const candidate of candidates) {
    try {
      mkdirSync(candidate, { recursive: false })
      return candidate
    } catch (e) {
      if ((e as NodeJS.ErrnoException).code === 'EEXIST') continue
      throw e
    }
  }
  throw new Error('Could not reserve a handover bundle directory (too many collisions).')
}

/**
 * TOCTOU guard: re-validate a bundle record against the paths vetted at
 * creation. Runs twice in runHandoverAgent — once at entry, and AGAIN after
 * resolveBrain() (whose auth/routing awaits are an unbounded gap) immediately
 * before the first RUN.log write/emit and the generate() call. Checks:
 *   1. re-realpath targetDir AND bundleDir — each must be EXACTLY the canonical
 *      path recorded at creation (any junction/rename swap changes the realpath);
 *   2. lstat-walk every component from the target down to the bundle dir — each
 *      must be a real directory, never a symlink/junction/reparse point
 *      (isSymbolicLink() does NOT match OneDrive/Dropbox cloud-file reparse
 *      tags, so cloud-synced folders are not falsely rejected);
 *   3. re-check containment: the bundle must still live under the target.
 * Returns null when intact, else a user-facing refusal reason; a refusal writes
 * nothing into the suspect directory.
 *
 * THREAT MODEL — what this defends and what it honestly cannot:
 * - DEFENDED: a compromised renderer (paths never trusted, only opaque ids) and
 *   accidental misselection/stale targets (moved/replaced folders are refused).
 * - RESIDUAL: a string cwd handed to child_process cannot provide race-free
 *   filesystem identity on Windows — a window remains inside generate()/runCli
 *   between this final validation and OS process creation.
 * - OUT OF SCOPE: a concurrent LOCAL attacker with user-level filesystem rights
 *   (able to swap directories mid-session) — such an attacker already has
 *   user-equivalent execution and needs no help from this code path.
 */
export function revalidateBundleRecord(record: BundleRecord): string | null {
  let realTarget: string
  let realBundle: string
  try {
    realTarget = realpathSync(record.targetDir)
    realBundle = realpathSync(record.bundleDir)
  } catch {
    return 'The handover bundle or its target folder no longer exists. Write the bundle again.'
  }

  // 1. Exact canonical equality with what was vetted at creation.
  if (comparable(realTarget) !== comparable(record.targetDir) || comparable(realBundle) !== comparable(record.bundleDir)) {
    return 'The handover target changed on disk since the bundle was written (moved or replaced by a link). Write the bundle again.'
  }

  // 2. No reparse points anywhere from the target down to the bundle dir.
  const rel = relative(record.targetDir, record.bundleDir)
  if (!rel || rel.startsWith('..') || parse(rel).root) {
    return 'The handover bundle is no longer inside its target folder. Write the bundle again.'
  }
  let walk = record.targetDir
  for (const segment of [null, ...rel.split(sep)]) {
    if (segment !== null) walk = join(walk, segment)
    try {
      const st = lstatSync(walk)
      if (st.isSymbolicLink() || !st.isDirectory()) {
        return 'A folder on the handover bundle path was replaced by a link. Write the bundle again.'
      }
    } catch {
      return 'The handover bundle path is no longer accessible. Write the bundle again.'
    }
  }

  // 3. Containment (belt-and-suspenders — implied by 1+2, but cheap to assert).
  if (!comparable(realBundle).startsWith(comparable(realTarget) + sep)) {
    return 'The handover bundle escaped its target folder. Write the bundle again.'
  }

  return null
}

/** Parse the transcript's stored action_items (JSON array or plain text) to markdown. */
function formatActionItems(raw: string | undefined, detected: Array<{ title: string; description?: string; type?: string; status?: string }>): string {
  const lines: string[] = ['# Action Items', '']
  const fromTranscript: string[] = []
  if (raw && raw.trim()) {
    try {
      const parsed = JSON.parse(raw)
      if (Array.isArray(parsed)) {
        for (const item of parsed) {
          if (typeof item === 'string') fromTranscript.push(item)
          else if (item && typeof item === 'object') {
            const owner = (item.owner || item.assignee || '').toString().trim()
            const task = (item.task || item.action || item.title || item.text || '').toString().trim()
            const due = (item.due || item.dueDate || '').toString().trim()
            const parts = [task, owner ? `— ${owner}` : '', due ? `(due ${due})` : ''].filter(Boolean)
            if (parts.length) fromTranscript.push(parts.join(' '))
          }
        }
      } else {
        fromTranscript.push(raw.trim())
      }
    } catch {
      fromTranscript.push(raw.trim())
    }
  }

  if (fromTranscript.length) {
    lines.push('## From the transcript', '')
    for (const t of fromTranscript) lines.push(`- ${t}`)
    lines.push('')
  }

  if (detected.length) {
    lines.push('## Detected actionables', '')
    for (const a of detected) {
      const suffix = a.status ? ` _(status: ${a.status})_` : ''
      lines.push(`- **${a.title}**${suffix}`)
      if (a.description && a.description.trim()) lines.push(`  ${a.description.trim()}`)
    }
    lines.push('')
  }

  if (!fromTranscript.length && !detected.length) {
    lines.push('None recorded.', '')
  }
  return lines.join('\n')
}

/** Resolve the full source (mirrors output-generator + resolveProjectFolderForActionable). */
function resolveSource(ref: HandoverSourceRef, deps: HandoverDataDeps): ResolvedSource {
  const actionableId = ref.actionableId ?? null
  let knowledgeCaptureId = ref.knowledgeCaptureId ?? null

  // An actionable's source_knowledge_id is either a capture id OR a recording id.
  let skid: string | null = knowledgeCaptureId
  if (actionableId) {
    const a = deps.getActionable(actionableId)
    if (a?.source_knowledge_id) skid = a.source_knowledge_id
  }

  const kc = skid ? deps.getKnowledgeCapture(skid) : undefined
  let recordingId = ref.recordingId ?? null
  let meetingId = ref.meetingId ?? null

  if (kc) {
    knowledgeCaptureId = kc.id
    recordingId = recordingId ?? kc.source_recording_id ?? null
    meetingId = meetingId ?? kc.meeting_id ?? null
  } else if (skid) {
    // No capture row → treat skid as a recording id.
    recordingId = recordingId ?? skid
  }

  const rec = recordingId ? deps.getRecording(recordingId) : undefined
  if (rec) meetingId = meetingId ?? rec.meeting_id ?? null

  // ADV16-4 (round-17) — a STANDALONE capture has NO recordingId, so the recording
  // gate below would let its title/summary/detected-actionables through unchecked
  // (and recordingIds=[] would make the later pre-write & pre-agent revalidations
  // pass on an empty array). Gate the resolved capture through the shared
  // fail-closed CAPTURE boundary (deleted_at + standalone quality, or recording
  // delegation) BEFORE reading any capture-derived derivative.
  if (knowledgeCaptureId && !deps.isCaptureEligible(knowledgeCaptureId)) {
    throw new Error(HANDOVER_INELIGIBLE_ERROR)
  }

  // RE7-2 (round-7) — resolve recording identity FIRST, then gate through the
  // shared fail-closed boundary BEFORE reading any transcript/summary/action
  // derivatives. A stale actionable/handover prompt must not export a
  // now-excluded recording to an agentic brain; abort fail-closed.
  if (recordingId && !deps.isRecordingEligible(recordingId)) {
    throw new Error(HANDOVER_INELIGIBLE_ERROR)
  }

  const transcript = recordingId ? deps.getTranscript(recordingId) : undefined
  const meeting = meetingId ? deps.getMeeting(meetingId) : undefined
  const knowledgeKey = knowledgeCaptureId ?? skid
  const detected = knowledgeKey ? deps.getActionablesForKnowledge(knowledgeKey) : []

  const title = (kc?.title || meeting?.subject || rec?.filename || 'handover').toString()
  const attendees = (meeting?.attendees || '')
    .split(/[;,\n]/)
    .map((s) => s.trim())
    .filter(Boolean)
  const recordingIds = recordingId ? [recordingId] : []

  const summaryText = (transcript?.summary || kc?.summary || 'No summary available.').trim() || 'No summary available.'
  const decisionsRaw = (transcript?.key_points || '').trim()
  const decisionsText = decisionsRaw
    ? `# Key Points / Decisions\n\n${decisionsRaw}`
    : '# Key Points / Decisions\n\nNone recorded.'

  return {
    actionableId,
    knowledgeCaptureId,
    meetingId,
    recordingIds,
    title,
    transcriptText: (transcript?.full_text || 'No transcript available.').trim() || 'No transcript available.',
    summaryText: `# Summary\n\n${summaryText}`,
    actionItemsText: formatActionItems(transcript?.action_items, detected),
    decisionsText,
    meetingJson: {
      subject: meeting?.subject ?? null,
      date: meeting?.start_time ?? rec?.date_recorded ?? null,
      attendees,
      meetingId,
      recordingIds,
      knowledgeCaptureId,
    },
  }
}

const README_BODY = `# HiDock Next — Handover Bundle

This folder was generated by **HiDock Next** to hand a meeting's follow-up work
to an AI coding agent (Claude Code / Codex / Gemini CLI).

**Start with \`HANDOVER.md\`** — it is a self-contained prompt describing the work
to do. The \`context/\` folder holds the supporting material the prompt refers to:

- \`context/transcript.md\` — the full meeting transcript
- \`context/summary.md\` — the analysis summary
- \`context/action-items.md\` — extracted action items and detected actionables
- \`context/decisions.md\` — key points / decisions
- \`context/meeting.json\` — meeting metadata (subject, date, attendees, ids)

\`manifest.json\` records which recording/meeting this came from, when it was
generated, and which AI brain was selected. If the agent was run in-app, its
progress and result are appended to \`RUN.log\`.
`

/**
 * Assemble the handover bundle on disk. Pure filesystem + DB reads — no LLM calls,
 * no network. The target directory is canonicalized and vetted (protected paths
 * rejected), the `handover` parent must not be a symlink/junction, the bundle dir
 * is reserved ATOMICALLY, and its real path is verified to be contained under the
 * canonical target — then the bundle is registered under an opaque bundleId which
 * is the only token `runAgent` accepts.
 */
export function assembleHandoverBundle(params: AssembleBundleParams): AssembleBundleResult {
  const now = (params.now ?? (() => new Date()))()
  const deps: HandoverDataDeps = { ...defaultDataDeps, ...(params.data ?? {}) }

  // 1. Canonicalize + vet the target (throws a user-facing error when refused).
  const canonicalTarget = validateTargetDir(params.targetDir, params.extraProtectedPaths ?? [])

  // 2. The `handover` parent must be a REAL directory directly under the target —
  //    a symlink/junction here would let bundle writes escape the vetted target.
  const parentDir = join(canonicalTarget, 'handover')
  try {
    const st = lstatSync(parentDir)
    if (st.isSymbolicLink() || !st.isDirectory()) {
      throw new Error('The "handover" folder inside the target is a link or not a directory. Remove it and retry.')
    }
  } catch (e) {
    if ((e as NodeJS.ErrnoException).code === 'ENOENT') {
      mkdirSync(parentDir) // non-recursive: canonicalTarget is known to exist
    } else {
      throw e
    }
  }

  const resolved = resolveSource(params.source, deps)
  // Slug = timestamp + slugify output: strictly [a-z0-9-], so no separators,
  // no dot segments, and (with the timestamp prefix) no Windows reserved names —
  // the transcript-derived title is untrusted input.
  const slug = `${timestampSlug(now)}-${slugify(resolved.title)}`

  // 3. Reserve the bundle directory atomically (no check-then-use window).
  const bundleDir = reserveBundleDir(parentDir, slug)

  // 4. Containment post-check: the REAL bundle path must live under the canonical
  //    target (belt-and-suspenders against reparse-point tricks between checks).
  const realBundle = comparable(realpathSync(bundleDir))
  if (realBundle !== comparable(bundleDir) || !realBundle.startsWith(comparable(canonicalTarget) + sep)) {
    throw new Error('Handover bundle path escaped the target directory — aborting.')
  }

  const contextDir = join(bundleDir, 'context')
  mkdirSync(contextDir)

  const files: Array<{ rel: string; content: string }> = [
    { rel: 'HANDOVER.md', content: params.handoverContent },
    { rel: 'README.md', content: README_BODY },
    { rel: 'context/transcript.md', content: `# Transcript\n\n${resolved.transcriptText}\n` },
    { rel: 'context/summary.md', content: `${resolved.summaryText}\n` },
    { rel: 'context/action-items.md', content: `${resolved.actionItemsText}\n` },
    { rel: 'context/decisions.md', content: `${resolved.decisionsText}\n` },
    { rel: 'context/meeting.json', content: JSON.stringify(resolved.meetingJson, null, 2) },
  ]

  const manifest: HandoverManifest = {
    slug,
    title: resolved.title,
    generatedAt: now.toISOString(),
    brain: params.brain ?? null,
    source: {
      actionableId: resolved.actionableId,
      knowledgeCaptureId: resolved.knowledgeCaptureId,
      meetingId: resolved.meetingId,
      recordingIds: resolved.recordingIds,
    },
    files: files.map((f) => f.rel).concat('manifest.json'),
  }

  // RE7-2 — revalidate eligibility IMMEDIATELY before the writes (the source
  // could have been trashed/personal/value-excluded between resolveSource and
  // here). Fail closed: abort the whole bundle rather than persist an excluded
  // recording's derivatives to disk. ADV16-4 (round-17): also revalidate the
  // resolved CAPTURE — a standalone excluded capture has an empty recordingIds
  // array, so the recording check alone would let it through.
  {
    if (resolved.knowledgeCaptureId && !deps.isCaptureEligible(resolved.knowledgeCaptureId)) {
      throw new Error(HANDOVER_INELIGIBLE_ERROR)
    }
    const { eligible, failClosed } = filterEligibleRecordingIds(resolved.recordingIds)
    if (failClosed || resolved.recordingIds.some((id) => !eligible.has(id))) {
      throw new Error(HANDOVER_INELIGIBLE_ERROR)
    }
  }

  for (const f of files) writeFileSync(join(bundleDir, f.rel), f.content, 'utf-8')
  writeFileSync(join(bundleDir, 'manifest.json'), JSON.stringify(manifest, null, 2), 'utf-8')

  // 5. Register under an opaque id — the only token runAgent accepts back.
  const bundleId = randomUUID()
  bundleRegistry.set(bundleId, { bundleDir, targetDir: canonicalTarget, createdAt: now.toISOString() })

  return { bundleId, bundleDir, handoverPath: join(bundleDir, 'HANDOVER.md'), targetDir: canonicalTarget, manifest }
}

// ── Agentic run ────────────────────────────────────────────────────────────────

export interface RunHandoverAgentParams {
  /**
   * Opaque bundle id minted by assembleHandoverBundle. The bundle/target paths
   * are looked up in the main-process registry — renderer-supplied paths are
   * NEVER accepted for execution.
   */
  bundleId: string
  /** Explicit brain to use; when absent the router resolves the 'handover' task. */
  brainId?: string
  signal?: AbortSignal
  /** Injected for tests. */
  now?: () => Date
  /** Injected for tests. */
  resolveBrain?: (brainId?: string) => Promise<AIBrain | null>
  /** Injected for tests. */
  emit?: (type: string, payload: Record<string, unknown>) => void
  /** Injected for tests. Defaults to the main-process bundle registry. */
  lookupBundle?: (bundleId: string) => BundleRecord | undefined
}

export interface RunHandoverAgentResult {
  ok: boolean
  brainId: string | null
  brainLabel: string | null
  finalResponse: string | null
  runLogPath: string
  error?: string
}

/**
 * Resolve the agentic brain for a run: an explicit, enabled, configured, agentic
 * brain wins; otherwise the BrainRouter resolves the 'handover' task with the
 * 'agentic' capability (respecting Settings default/routing). Returns null when no
 * agentic brain is usable — the caller surfaces that as a failure, never silence.
 */
async function defaultResolveBrain(brainId?: string): Promise<AIBrain | null> {
  if (brainId) {
    const brain = getBrainRegistry().get(brainId as AIBrain['id'])
    if (brain && brain.capabilities().has('agentic')) {
      try {
        if ((await brain.authStatus()).configured) return brain
      } catch {
        /* fall through to the router */
      }
    }
  }
  return getBrainRouter().resolve('handover', 'agentic')
}

function buildRunPrompt(bundleDir: string, targetDir: string): string {
  const handoverPath = join(bundleDir, 'HANDOVER.md')
  const contextDir = join(bundleDir, 'context')
  return [
    'You are receiving a handover of follow-up work from HiDock Next.',
    '',
    `A handover bundle has been written to:`,
    `  ${bundleDir}`,
    '',
    `1. First read the handover prompt: "${handoverPath}".`,
    `2. Then read the supporting material in "${contextDir}" (transcript, summary, action items, decisions, meeting metadata).`,
    '',
    `Your working directory for this task is:`,
    `  ${targetDir}`,
    '',
    'Carry out the follow-up work described in the handover prompt, operating inside that working directory.',
  ].join('\n')
}

/**
 * Run the handover through an agentic brain, in-app. The bundle/target paths come
 * ONLY from the main-process registry (opaque bundleId); one run per bundle at a
 * time. Writes a RUN.log alongside the bundle and emits event-bus events so the
 * Activity Log can surface progress. Uses the brain's `generate()` as the
 * invocation surface — the validated target directory is passed as the child
 * process cwd (GenerateOptions.cwd) — and honours the never-throw / null
 * contract: a null result is a surfaced failure written to RUN.log, not silence.
 */
/**
 * RE7-2 (round-7) — final eligibility gate before an agent run. Reads the
 * bundle's manifest recordingIds and re-validates them through the shared
 * fail-closed boundary: the source could have been trashed / personal /
 * value-excluded since the bundle was assembled. Returns an error string when
 * the run must be refused, or null when eligible. A read/parse failure is
 * treated as fail-closed (refuse).
 */
function revalidateBundleEligibility(bundleDir: string): string | null {
  let recordingIds: string[]
  let knowledgeCaptureId: string | null
  try {
    const manifest = JSON.parse(readFileSync(join(bundleDir, 'manifest.json'), 'utf-8')) as HandoverManifest
    recordingIds = manifest.source?.recordingIds ?? []
    knowledgeCaptureId = manifest.source?.knowledgeCaptureId ?? null
  } catch (e) {
    console.error('[handover] could not read bundle manifest for eligibility re-check — failing closed:', e)
    return HANDOVER_INELIGIBLE_ERROR
  }
  // ADV16-4 (round-17) — revalidate the resolved CAPTURE too. A STANDALONE
  // capture has no recordingId, so a recording-only check would run an agent over
  // an excluded standalone capture's derivatives. isCaptureEligible is
  // fail-closed (excluded / soft-deleted / value-excluded / lookup error ⇒ false).
  if (knowledgeCaptureId && !isCaptureEligible(knowledgeCaptureId)) return HANDOVER_INELIGIBLE_ERROR
  if (recordingIds.length === 0) return null // no recording-backed content
  const { eligible, failClosed } = filterEligibleRecordingIds(recordingIds)
  if (failClosed || recordingIds.some((id) => !eligible.has(id))) return HANDOVER_INELIGIBLE_ERROR
  return null
}

export async function runHandoverAgent(params: RunHandoverAgentParams): Promise<RunHandoverAgentResult> {
  const now = params.now ?? (() => new Date())
  const resolveBrain = params.resolveBrain ?? defaultResolveBrain
  const lookupBundle = params.lookupBundle ?? getRegisteredBundle
  const emit =
    params.emit ??
    ((type: string, payload: Record<string, unknown>) =>
      getEventBus().emitDomainEvent({ type, timestamp: now().toISOString(), payload }))

  // Only bundles minted by this process are runnable — a forged/unknown id (or a
  // path smuggled in as an id) resolves to nothing and is refused. The registry
  // is session-only, so this is also the "app restarted since the bundle was
  // written" path — surfaced as a friendly "expired" message.
  const record = lookupBundle(params.bundleId)
  if (!record) {
    const error = BUNDLE_EXPIRED_ERROR
    emit('handover:run-failed', { bundleId: params.bundleId, brainId: params.brainId ?? null, error })
    return { ok: false, brainId: params.brainId ?? null, brainLabel: null, finalResponse: null, runLogPath: '', error }
  }
  const { bundleDir, targetDir } = record
  const runLogPath = join(bundleDir, 'RUN.log')

  // Early TOCTOU check: refuse an already-tampered bundle before spending time
  // on brain auth probes. NOT the authoritative check — that re-runs after
  // resolveBrain(), immediately before the first write/spawn (see below).
  const tamper = revalidateBundleRecord(record)
  if (tamper) {
    emit('handover:run-failed', { bundleId: params.bundleId, brainId: params.brainId ?? null, error: tamper })
    return { ok: false, brainId: params.brainId ?? null, brainLabel: null, finalResponse: null, runLogPath, error: tamper }
  }

  // One run per bundle: a second concurrent run would interleave RUN.log lines
  // indistinguishably and double-execute the same work.
  if (activeRuns.has(params.bundleId)) {
    const error = 'This handover bundle already has an agent run in progress.'
    emit('handover:run-failed', { bundleId: params.bundleId, brainId: params.brainId ?? null, error })
    return { ok: false, brainId: params.brainId ?? null, brainLabel: null, finalResponse: null, runLogPath, error }
  }
  activeRuns.add(params.bundleId)

  const appendLog = (line: string) => {
    try {
      appendFileSync(runLogPath, line.endsWith('\n') ? line : `${line}\n`, 'utf-8')
    } catch (e) {
      console.error('[handover] failed to append RUN.log:', e)
    }
  }

  try {
    const brain = await resolveBrain(params.brainId)

    // FINAL TOCTOU re-check, at the last moment we control: resolveBrain() above
    // awaits auth probes / routing (an unbounded gap in which the filesystem can
    // change), so the pre-gap check alone is not enough. Re-run the cheap
    // realpath/lstat validation AFTER resolution and IMMEDIATELY before the
    // first RUN.log write / emit into the bundle and the generate() call. A
    // refusal here writes NOTHING into the (possibly swapped) directory.
    const lateTamper = revalidateBundleRecord(record)
    if (lateTamper) {
      emit('handover:run-failed', { bundleId: params.bundleId, brainId: params.brainId ?? null, error: lateTamper })
      return {
        ok: false,
        brainId: params.brainId ?? null,
        brainLabel: null,
        finalResponse: null,
        runLogPath,
        error: lateTamper,
      }
    }

    // RE7-2 — final eligibility re-check, at the same last-moment gate as the
    // tamper check: refuse the run (write nothing, spawn nothing) if the source
    // recording became excluded since the bundle was assembled.
    const ineligible = revalidateBundleEligibility(bundleDir)
    if (ineligible) {
      emit('handover:run-failed', { bundleId: params.bundleId, brainId: params.brainId ?? null, error: ineligible })
      return { ok: false, brainId: params.brainId ?? null, brainLabel: null, finalResponse: null, runLogPath, error: ineligible }
    }

    if (!brain) {
      const error =
        'No agentic AI brain is available. Enable and sign in to Claude Code, Codex, or Gemini CLI in Settings → AI Brains.'
      appendLog(`[${now().toISOString()}] HANDOVER RUN FAILED — ${error}`)
      emit('handover:run-failed', { bundleDir, brainId: params.brainId ?? null, error })
      return { ok: false, brainId: params.brainId ?? null, brainLabel: null, finalResponse: null, runLogPath, error }
    }

    // Fail closed on cwd: only brains advertising 'agentic' honour
    // GenerateOptions.cwd (they spawn a CLI via runCli). Refuse anything else
    // rather than silently running in Electron's cwd.
    if (!brain.capabilities().has('agentic')) {
      const error = `The selected brain (${brain.label}) cannot run in a working directory. Pick an agentic brain.`
      appendLog(`[${now().toISOString()}] HANDOVER RUN FAILED — ${error}`)
      emit('handover:run-failed', { bundleDir, brainId: brain.id, error })
      return { ok: false, brainId: brain.id, brainLabel: brain.label, finalResponse: null, runLogPath, error }
    }

    const started = now().toISOString()
    appendLog(`[${started}] HANDOVER RUN STARTED`)
    appendLog(`  brain: ${brain.label} (${brain.id})`)
    appendLog(`  target: ${targetDir}`)
    appendLog(`  bundle: ${bundleDir}`)
    appendLog('')
    emit('handover:run-started', { bundleDir, brainId: brain.id, targetDir })

    const prompt = buildRunPrompt(bundleDir, targetDir)

    let finalResponse: string | null = null
    try {
      // `generate()` NEVER throws by contract — it returns null on failure/cancel.
      // cwd = the validated target: the CLI child process actually runs there.
      finalResponse = await brain.generate([{ role: 'user', content: prompt }], {
        signal: params.signal,
        cwd: targetDir,
      })
    } catch (e) {
      // Defensive: even though the contract forbids it, never let a throw escape.
      console.error('[handover] brain.generate threw (contract violation):', e)
      finalResponse = null
    }

    const ended = now().toISOString()
    if (finalResponse && finalResponse.trim()) {
      appendLog(finalResponse.trim())
      appendLog('')
      appendLog(`[${ended}] HANDOVER RUN COMPLETED`)
      emit('handover:run-completed', { bundleDir, brainId: brain.id, ok: true })
      return { ok: true, brainId: brain.id, brainLabel: brain.label, finalResponse: finalResponse.trim(), runLogPath }
    }

    const error =
      'The agent returned no output — it may have failed, been cancelled, timed out, or not be authenticated. Check Settings → AI Brains.'
    appendLog(`[${ended}] HANDOVER RUN FAILED — ${error}`)
    emit('handover:run-failed', { bundleDir, brainId: brain.id, error })
    return { ok: false, brainId: brain.id, brainLabel: brain.label, finalResponse: null, runLogPath, error }
  } finally {
    activeRuns.delete(params.bundleId)
  }
}
