/**
 * Recording deletion service (privacy source-deletion, v38).
 *
 * Coordinates the two user intents from the DB cascade with the on-disk side
 * effects the database layer cannot do itself:
 *
 *  - "Mark personal" (markPersonal): a reversible, non-destructive flag. The DB
 *    layer pulls the recording out of every AI pipeline + default surface; no
 *    file is touched.
 *  - Delete (deleteRecording): soft by default (hide + restorable) or hard
 *    ({ hard: true }, the privacy case) which removes ALL derived DB rows via
 *    deleteRecordingCascade, then unlinks the on-disk files here — the audio,
 *    the exported wiki .md, and any artifact blobs — and clears the in-memory
 *    vector store so nothing survives.
 *
 * The DEVICE copy is intentionally never touched (USB safety); removing it is a
 * separate, explicit action out of scope here.
 *
 * F17/T6 (spec-006) additions: `opts.skipGraphCleanup` threads AR3-3(c)'s
 * escape hatch through to the cascade; a hard purge's post-commit file
 * cleanup now tracks PER-TARGET outcomes and durably records any failures
 * (AR3-2) instead of only logging a warning, with a bounded, non-fatal retry
 * sweep (retryPendingFileCleanups) piggybacked on every hard purge and
 * available as its own IPC for a Trash-view-entry sweep.
 */

import { existsSync, unlinkSync } from 'fs'
import {
  deleteRecordingCascade,
  restoreRecording,
  setRecordingPersonal,
  getRecordingDeletionImpact,
  recordPendingFileCleanups,
  getPendingFileCleanups,
  updatePendingFileCleanups,
  removeDeviceFileCacheEntry,
  retryPendingGraphCleanups,
  type RecordingDeletionResult,
  type RecordingDeletionImpact,
  type PendingCleanupTarget
} from './database'
import { deleteRecording as deleteRecordingFile } from './file-storage'
import { removeMeetingWiki, reconcileWikiEligibility } from './meeting-wiki'
import { getVectorStore } from './vector-store'
import { getJensenDevice } from './jensen'
import { serializeDeviceOperation } from './device-operation-serializer'

export interface DeleteRecordingOutcome extends RecordingDeletionResult {
  success: true
  filesRemoved: {
    audio: boolean
    wikiPages: number
    artifactBlobs: number
  }
  /**
   * F17/T6 AR3-2 — true only when EVERY file-cleanup target that needed
   * removal was confirmed removed, including any the piggybacked retry sweep
   * cleared before this call returned. The caller's completion toast must
   * show plain success ONLY when this is true; otherwise an honest partial
   * ("N couldn't be deleted; will retry automatically"). Always true for a
   * soft delete (no files are touched).
   */
  allFilesRemoved: boolean
  /** Kinds still pending after the retry sweep (empty when allFilesRemoved). */
  pendingFileKinds: string[]
  /**
   * ADV49-1 (round 51, DELETION HONESTY) — true when a hard purge removed the
   * authoritative rows but could NOT durably journal a failed file-cleanup
   * target (the `recordPendingFileCleanups` write itself threw). The failed
   * paths are therefore unrecoverable by the retry sweep, so the caller must
   * NOT claim an automatic retry — it must report an honest unrecoverable
   * cleanup failure. Always false/absent when journaling succeeded (the normal
   * partial-failure case, which IS auto-retried). Never set for a soft delete.
   */
  cleanupUnrecoverable?: boolean
}

export interface DeletionServiceError {
  success: false
  error: string
  /**
   * F17/T6 AR3-1/AR3-3 — set when this specific failure means "the graph
   * cleanup seam is unavailable" (the fail-closed seam-null throw inside the
   * cascade transaction — AR3-1). The IPC handler layer's own
   * ensureGraphReady() pre-flight (AR3-3a) short-circuits BEFORE this
   * function is even called and sets the same flag on its own response.
   * Either way, the caller uses this to offer the explicit skipGraphCleanup
   * escape hatch — never automatically.
   */
  graphUnavailable?: boolean
}

/**
 * Mark / unmark a recording personal ("ignore"). Reversible. Returns the new
 * flag state, or an error if the recording is unknown. No files are touched —
 * the recording simply drops out of AI processing and default surfaces, and its
 * chunks stop appearing in RAG answers (filtered at query time).
 */
export function markRecordingPersonal(
  recordingId: string,
  personal: boolean
): { success: true; personal: boolean } | DeletionServiceError {
  const result = setRecordingPersonal(recordingId, personal)
  if (result === undefined) {
    return { success: false, error: `Recording ${recordingId} not found` }
  }
  // RE7-1 (round-7) — a personal TRANSITION removes any exported wiki page for a
  // now-ineligible recording (regenerated by the backfill when un-marked).
  reconcileWikiEligibility(recordingId)
  return { success: true, personal: result }
}

/** Read-only impact of a hard purge, for the confirm dialog. */
export function getDeletionImpact(recordingId: string): RecordingDeletionImpact | undefined {
  return getRecordingDeletionImpact(recordingId)
}

/** True when a cascade-throw message means "the graph cleanup seam itself is
 *  unavailable" (AR3-1's fail-closed refusal), distinct from any other
 *  cascade failure — matches the exact wording database.ts throws. */
function isGraphUnavailableMessage(message: string): boolean {
  return /graph cleanup unavailable/i.test(message)
}

/**
 * Delete a recording and everything derived from it. Soft by default (restorable
 * tombstone, no files removed); hard purge irreversibly removes derived rows +
 * files. Returns a summary of exactly what was removed.
 */
export async function deleteRecording(
  recordingId: string,
  opts: { hard?: boolean; skipGraphCleanup?: boolean } = {}
): Promise<DeleteRecordingOutcome | DeletionServiceError> {
  let cascade: RecordingDeletionResult | undefined
  try {
    cascade = deleteRecordingCascade(recordingId, opts)
  } catch (e) {
    const message = e instanceof Error ? e.message : 'Cascade delete failed'
    return {
      success: false,
      error: message,
      ...(isGraphUnavailableMessage(message) ? { graphUnavailable: true } : {})
    }
  }
  if (!cascade) {
    return { success: false, error: `Recording ${recordingId} not found` }
  }

  // RE7-1 (round-7) — a SOFT delete leaves derived files in place, but the wiki
  // markdown is an external-agent-readable EXPORT, so remove it on the soft
  // transition too (a hard purge already removes it via removeMeetingWiki
  // below). Regenerated on restore by the backfill / next transcription.
  if (cascade.mode === 'soft') {
    reconcileWikiEligibility(recordingId)
  }

  const filesRemoved = { audio: false, wikiPages: 0, artifactBlobs: 0 }
  const pendingTargets: PendingCleanupTarget[] = []
  // ADV49-1 (round 51) — set when the durable journaling of failed cleanup
  // targets itself fails, meaning those targets can never be auto-retried.
  let cleanupUnrecoverable = false

  if (cascade.mode === 'hard') {
    // Sync the in-memory vector store (its DB rows are already gone).
    try {
      await getVectorStore().deleteByRecording(recordingId)
      // The binary vector cache holds this recording's vectors ON DISK —
      // "permanent deletion" must not leave them recoverable until the next
      // boot's fingerprint invalidation. Delete the cache file now; the next
      // boot SQL-loads (sans purged rows) and rewrites it clean.
      getVectorStore().invalidateCache()
    } catch (e) {
      console.warn('[RecordingDeletion] vector store sync failed:', e)
      pendingTargets.push({ kind: 'vector' })
    }

    // Audio file on disk (data path). Never the device copy. A `false`
    // return from deleteRecordingFile is only a REAL failure worth tracking
    // when the file existed and the unlink attempt still didn't remove it —
    // if it was already gone, there's nothing left to clean up.
    if (cascade.filePath) {
      const pathExisted = existsSync(cascade.filePath)
      try {
        filesRemoved.audio = deleteRecordingFile(cascade.filePath)
      } catch (e) {
        console.warn('[RecordingDeletion] audio unlink failed:', e)
      }
      if (!filesRemoved.audio && pathExisted) {
        pendingTargets.push({ kind: 'audio', path: cascade.filePath })
      }
    }

    // Exported wiki markdown. RE7-P1b — removeMeetingWiki now surfaces FS
    // failures; a page that could not be removed is queued for retry rather than
    // silently reported as purged.
    try {
      const wiki = removeMeetingWiki(recordingId)
      filesRemoved.wikiPages = wiki.removed
      if (!wiki.ok) {
        console.warn(`[RecordingDeletion] wiki purge incomplete for ${recordingId} (failed=${wiki.failed})`)
        pendingTargets.push({ kind: 'wiki' })
      }
    } catch (e) {
      console.warn('[RecordingDeletion] wiki purge failed:', e)
      pendingTargets.push({ kind: 'wiki' })
    }

    // Artifact blobs.
    for (const path of cascade.artifactPaths) {
      try {
        if (existsSync(path)) {
          unlinkSync(path)
          filesRemoved.artifactBlobs++
        }
      } catch (e) {
        console.warn(`[RecordingDeletion] artifact blob unlink failed for ${path}:`, e)
        pendingTargets.push({ kind: 'artifact', path })
      }
    }

    // AR3-2 — durably record any first-attempt failures against this purge's
    // own journal row (deleteRecordingCascade always sets journalId for a
    // hard purge) so the retry sweep can rediscover and re-clean them.
    //
    // ADV49-1 (round 51, DELETION HONESTY): the authoritative recording/capture
    // rows are already committed and gone; this journal write is the ONLY
    // durable record of a cleanup target that could not be removed. If it FAILS
    // we must NOT swallow it and return a plain success that promises an
    // automatic retry which can never happen — the failed paths live only in
    // the in-memory `pendingTargets` and would be lost the moment this call
    // returns, leaving sensitive audio/artifacts on disk forever after a
    // "permanent deletion". Instead flag an explicit UNRECOVERABLE-cleanup
    // outcome so the caller reports an honest failure (the rows WERE purged, but
    // file cleanup could not be guaranteed and will NOT be auto-retried).
    if (pendingTargets.length > 0 && cascade.journalId) {
      try {
        recordPendingFileCleanups(cascade.journalId, pendingTargets)
      } catch (e) {
        console.error(
          '[RecordingDeletion] UNRECOVERABLE: failed to journal pending file cleanups — these targets cannot be auto-retried:',
          e
        )
        cleanupUnrecoverable = true
      }
    }
  }

  // AR3-2 — every hard purge piggybacks a bounded, non-fatal retry sweep of
  // ANY pending file-cleanup backlog: this purge's own failures above, plus
  // any older ones left by a previous purge. Never fatal to this call — a
  // sweep failure just means the pre-sweep counts stand.
  let allFilesRemoved = pendingTargets.length === 0
  let pendingFileKinds: string[] = pendingTargets.map((t) => t.kind)
  if (cascade.mode === 'hard') {
    // ARF-4 — opportunistically finish any DEFERRED graph cleanup left by an
    // earlier skipGraphCleanup escape-hatch purge. Non-fatal, and skipped in
    // practice for the escape-hatch purge that just deferred (the graph seam
    // was unavailable a moment ago); a later HEALTHY hard purge — or the
    // Trash-view-entry sweep — is what actually clears it.
    try {
      retryPendingGraphCleanups()
    } catch (e) {
      console.warn('[RecordingDeletion] pending graph-cleanup retry sweep failed (non-fatal):', e)
    }
    try {
      const sweep = await retryPendingFileCleanups()
      if (cascade.journalId) {
        const stillPending = sweep.stillPending[cascade.journalId]
        if (stillPending !== undefined) {
          // Swept, and something is STILL pending — report the post-sweep set.
          allFilesRemoved = stillPending.length === 0
          pendingFileKinds = stillPending
        } else if (sweep.clearedJournalIds.includes(cascade.journalId)) {
          // OP-LOW-2 (T6 fix round): the sweep CLEARED this purge's own fresh
          // failure within the same call — previously indistinguishable from
          // "not swept" (both were `undefined` in stillPending), which kept
          // the stale pre-sweep counts and over-warned "will retry" on a
          // purge whose cleanup had in fact fully completed.
          allFilesRemoved = true
          pendingFileKinds = []
        }
        // else: this journal row wasn't in the sweep window (bounded limit) —
        // keep the pre-sweep counts. Safe direction: over-warns, never
        // over-claims.
      }
    } catch (e) {
      console.warn('[RecordingDeletion] pending-cleanup retry sweep failed (non-fatal):', e)
    }
  }

  // ADV49-1 (round 51) — a journaling failure means the failed targets were
  // never persisted, so the sweep above could not (and did not) recover them.
  // Report an HONEST unrecoverable outcome: cleanup is not complete and will
  // NOT be auto-retried. (allFilesRemoved is already false here since
  // pendingTargets was non-empty, but force it for clarity.)
  if (cleanupUnrecoverable) {
    allFilesRemoved = false
    return { success: true, ...cascade, filesRemoved, allFilesRemoved, pendingFileKinds, cleanupUnrecoverable: true }
  }

  return { success: true, ...cascade, filesRemoved, allFilesRemoved, pendingFileKinds }
}

/**
 * F17/T6 AR3-2 — bounded, non-fatal retry sweep for post-commit file-cleanup
 * targets that failed on an earlier hard purge. Invoked from every hard
 * `deleteRecording` call above, AND from a small standalone IPC
 * (recordings:retryPendingCleanups) the renderer calls on Trash-view entry.
 * Never throws — a failure here must never block or fail the caller's own
 * action.
 */
export function retryPendingFileCleanups(
  limit = 25
): Promise<{
  attempted: number
  cleared: number
  /** OP-LOW-2: journal ids the sweep fully cleared, so a same-call caller can
   *  distinguish "swept clean" from "not swept at all" (both used to be an
   *  absent stillPending key). */
  clearedJournalIds: string[]
  stillPending: Record<string, string[]>
}> {
  // All entry points share the same Jensen command chain. In particular, the
  // renderer's startup/Trash sweep can arrive while the connect sweep is still
  // running; serializing the complete read-delete-write pass prevents both
  // callers from reading the same pending rows and issuing duplicate DELETE_FILE
  // commands, and prevents scans/downloads from interleaving between deletes.
  return serializeDeviceOperation(() => retryPendingFileCleanupsExclusive(limit))
}

async function retryPendingFileCleanupsExclusive(
  limit: number
): Promise<{
  attempted: number
  cleared: number
  clearedJournalIds: string[]
  stillPending: Record<string, string[]>
}> {
  const stillPending: Record<string, string[]> = {}
  const clearedJournalIds: string[] = []
  let attempted = 0
  let cleared = 0
  try {
    const rows = getPendingFileCleanups(limit)
    for (const row of rows) {
      attempted++
      const remaining: PendingCleanupTarget[] = []
      for (const target of row.targets) {
        const ok = await retryOneCleanupTarget(row.recordingId, target)
        if (!ok) remaining.push(target)
      }
      updatePendingFileCleanups(row.journalId, remaining)
      if (remaining.length === 0) {
        cleared++
        clearedJournalIds.push(row.journalId)
      } else {
        stillPending[row.journalId] = remaining.map((t) => t.kind)
      }
    }
  } catch (e) {
    console.warn('[RecordingDeletion] retryPendingFileCleanups failed (non-fatal):', e)
  }
  return { attempted, cleared, clearedJournalIds, stillPending }
}

/** Re-attempt exactly one pending cleanup target. Returns true when it is now
 *  confirmed clean (including "there was never anything there"). */
async function retryOneCleanupTarget(recordingId: string, target: PendingCleanupTarget): Promise<boolean> {
  try {
    switch (target.kind) {
      case 'audio':
        if (!target.path) return true
        // CX-T6-2/OP-LOW-1 (T6 fix round): an already-gone file IS clean —
        // deleteRecordingFile returns false for a missing path, which
        // previously kept an externally-removed (or actually-unlinked-but-
        // reported-false) pending audio target failing forever, so the
        // ledger row was retried futilely on every sweep. Mirrors the
        // artifact branch's guard below.
        if (!existsSync(target.path)) return true
        return deleteRecordingFile(target.path)
      case 'artifact':
        if (!target.path) return true
        if (!existsSync(target.path)) return true
        unlinkSync(target.path)
        return true
      case 'wiki':
        // RE7-P1b — only clear the pending target when the page is actually gone;
        // a persistent FS failure keeps it queued for the next sweep.
        return removeMeetingWiki(recordingId).ok
      case 'vector':
        await getVectorStore().deleteByRecording(recordingId)
        getVectorStore().invalidateCache()
        return true
      case 'device': {
        // Deferred hardware erase (2026-07-22): the user checked "Also delete
        // from device" while the device was DISCONNECTED. Attempt the USB
        // delete; on any failure (still disconnected / device error) keep the
        // target pending for the next sweep (device-connect or hard purge).
        if (!target.path) return true
        const result = await getJensenDevice().deleteFile(target.path)
        if (result?.result !== 'success' && result?.result !== 'not-exists') return false
        // The hard purge already removed the recording row, but the renderer's
        // offline device cache can still resurrect it as a ghost device-only
        // item. A successful deferred erase must reconcile that cache just like
        // the immediate permanent-delete path does.
        removeDeviceFileCacheEntry(target.path)
        return true
      }
      default:
        return true
    }
  } catch (e) {
    console.warn(`[RecordingDeletion] retry failed for ${target.kind}:`, e)
    return false
  }
}

/**
 * "Also delete from device" while the device may be disconnected: attempt the
 * USB delete NOW; on failure durably journal it as a pending 'device' cleanup
 * so the next sweep (device connect, hard purge, or Trash entry) erases it.
 */
export async function queueDeviceDelete(
  deviceFilename: string,
  journalId: string
): Promise<{ deletedNow: boolean; queued: boolean }> {
  try {
    const result = await serializeDeviceOperation(() => getJensenDevice().deleteFile(deviceFilename))
    if (result?.result === 'success' || result?.result === 'not-exists') {
      return { deletedNow: true, queued: false }
    }
  } catch {
    /* fall through to journaling */
  }
  recordPendingFileCleanups(journalId, [{ kind: 'device', path: deviceFilename }])
  console.log(`[RecordingDeletion] device copy of ${deviceFilename} queued for deletion on next sweep`)
  return { deletedNow: false, queued: true }
}

/**
 * Restore a soft-deleted recording (undo). Returns success=false if there is no
 * soft-deleted recording with this id (e.g. it was hard-purged).
 */
export function restoreDeletedRecording(
  recordingId: string
): { success: boolean } {
  return { success: restoreRecording(recordingId) }
}
